### ISSUE TITLE
[BUG] dsu version 2.4.4

### ISSUE THREAD

**Issue by chibeepatag** [gangelo/dsu#74]
Escape characters show when I do dsu browse

**To Reproduce**
1. Do `dsu browse w`

**Expected behavior**
Escape characters should not show. Text should appear as you do dsu list t

<img width="849" alt="Screenshot 2024-01-31 at 8 36 36 PM" src="https://github.com/gangelo/dsu/assets/7259143/af9d1608-69f7-476a-97df-a86fd2115bfb">

**Desktop (please complete the following information):**
 - dsu version 2.4.4
 - Ruby version ruby 3.1.2p20
 - OS: macOS 13.4

**Additional context**
Terminal: iTerm
also tried in the stock terminal of mac   with zsh

**Comment by gangelo** [comment]
Can you try this to see if the problem replicates itself?: 
`dsu theme show default | less`

Then, try this to see if the problem rectifies itself?:
`dsu theme show default | less -R`

**Comment by gangelo** [comment]
Thank you [chibeepatag](https://github.com/chibeepatag). I think the problem may have been that you might have typed `-R` while browsing your entries using `dsu browse w`? -R will tell `less` to toggle escape sequencing on/off. If this behavior is persistent, can you check to see if you've enabled less to always turn escape sequences off (e.g. export LESS='-R') in any of your env files (like .bashrc or .zshrc)? This will cause less to always turn escaping off. If you want to keep that setting, just type `-R` while browsing your entries and all should be well. Let me know.

**Comment by chibeepatag** [comment]
dsu browse w then -R does fix it.  Thanks!

Here are some screencaps in case you want to look into this further. I'm good with doing -R any case. :-)
dsu theme show default
![Screenshot 2024-02-01 at 5 27 32 AM](https://github.com/gangelo/dsu/assets/7259143/efb0972f-f50d-49c2-8825-9f9632d5ae1d)

dsu browse w
![Screenshot 2024-02-01 at 5 29 23 AM](https://github.com/gangelo/dsu/assets/7259143/97c2669d-178a-4c88-a446-4590bd14da06)

dsu browse w   --> then -R
![Screenshot 2024-02-01 at 5 30 10 AM](https://github.com/gangelo/dsu/assets/7259143/630d3725-39cf-44ae-9ca7-ab51a446782d)

less somefile
![Screenshot 2024-02-01 at 5 34 38 AM](https://github.com/gangelo/dsu/assets/7259143/9ade8411-d786-441b-a529-cbd7b2d703cc)

**Comment by gangelo** [comment]
> dsu browse w then -R does fix it. Thanks!

Thanks Celine, I'll continue to look into this; however, I am of the opinion that you may have `less` settings in your environment forcing the behavior. If you don't mind, I am going to close this out, but I will continue to look into whether or not this is something I can remedy on our end.

**Comment by gangelo** [comment]
Closing this as user environment-specific. Will keep an eye out for recurring complaints and look into whether or not this is something we can mitigate on our end.
